<template>
    <main>
        <div>
            <router-link :to="'/new/'"><a>+</a></router-link>
        </div>
        <h1>Contacts</h1>
        <form>
            <input class="search" type="search" name="search" placeholder="Search" v-model="search">
        </form>
        <!-- use <router-link> to link to a router / go to another 'page' -->
        <!-- in this project, click on the contact name will go the detailed page so we need to use <router-link> here -->
        <router-link
            v-for="contact in filteredContacts"
            :to="'/contact/' + contact.id">
            <a><p>{{ contact.firstName}} {{ contact.lastName }}</p></a>
        </router-link>
        
    </main>
</template>

<script>
// collection, query, onSnapshot, orderBy are firebase methods used to retrieve data. onSnapshot provides realtime updates
import { collection, query, onSnapshot, orderBy } from 'firebase/firestore'
import db from '../db.js'

export default {
    name: 'Contacts',
    data: function () {
        // these empty array will store anything in database if there is any
        return {
            contacts: [],
            search: ''
        }
    },

    // make a request to the firestore database
    created: function () {
        // contacts is the name of the firestore collection we want to retrieve
        const q = query(collection(db, 'contacts'), orderBy('lastName'))
        // onSnapshot method itself will refresh all the existing data, includes both the old ones and the latest one
        // but we only want the new one to be pushed into the empty array: contacts: []
        // code block below is meant to realize this
        onSnapshot(q, (snapshot) => {
            // the empty data array will carry the new data
            const data = []
            // forEach is a firebase method
            snapshot.forEach((doc) => data.push({
                // this id is the document id automatically generated by firestore
                id: doc.id,
                firstName: doc.data().firstName,
                lastName: doc.data().lastName,
                email: doc.data().email
            }))
            // update contacts: []
            this.contacts = data
        })
    },

    computed: {
        filteredContacts: function () {
            if (this.search) {
                return this.contacts.filter(contact => contact.firstName.toLowerCase() === this.search || contact.lastName.toLowerCase() === this.search)
            } else {
                return this.contacts
            }    
        }
    }
}
</script>

<style scoped>
    main {
        width: 50%;
        height: 600px;
        margin: 80px auto auto auto;
        padding: 40px;
        background-color: white;
    }
    div {
        display: flex;
        justify-content: end;
    }
    a {
        font-size: 30px;
        text-decoration: none;
        color: black;
    }
    a:hover, a:active {
        color: #177DDA;
    }
    a:link, a:visited {
        color: #177DDA;
    }
    h1 {
        font-size: 70px;
        font-family: 'Nanum Gothic', sans-serif;
    }
    input {
        width: 100%;
        padding: 10px;
        border-radius: 5px;
        border-style: solid;
        font-size: 20px;
        font-family: 'Roboto', sans-serif;
    }
    p {
        font-family: 'Roboto', sans-serif;
    }
</style>